"""
Test script for the business logic services.
"""
import asyncio
from bot.database.base import get_session, engine
from bot.services.config_service import ConfigService
from bot.services.subscription_service import SubscriptionService
from bot.services.channel_service import ChannelManagementService


async def test_services():
    """
    Test the services as specified in the requirements:
    1. Initialize Config
    2. Generate a token
    3. Validate the token
    4. Create a subscription
    """
    print("Starting service tests...")
    
    # Get a database session
    async for session in get_session():
        print("✓ Got database session")
        
        # 1. Test ConfigService - Initialize Config
        print("\n1. Testing ConfigService...")
        try:
            config = await ConfigService.get_bot_config(session)
            print(f"✓ Config retrieved: ID {config.id}")
            
            # Update a config field to test update functionality
            updated_config = await ConfigService.update_config(
                session, 
                "vip_channel_id", 
                "test_channel_id"
            )
            print(f"✓ Config updated: VIP channel ID set to {updated_config.vip_channel_id}")
        except Exception as e:
            print(f"✗ ConfigService test failed: {e}")
            return
        
        # 2. Test SubscriptionService - Generate a token
        print("\n2. Testing SubscriptionService - Token Generation...")
        try:
            token = await SubscriptionService.generate_vip_token(
                session, 
                admin_id=123456, 
                duration_hours=24
            )
            print(f"✓ VIP token generated: {token.token[:8]}...")
            print(f"  - Duration: {token.duration_hours} hours")
            print(f"  - Generated by: {token.generated_by}")
        except Exception as e:
            print(f"✗ Token generation failed: {e}")
            return
        
        # 3. Test SubscriptionService - Validate the token
        print("\n3. Testing SubscriptionService - Token Validation...")
        try:
            validated_token = await SubscriptionService.validate_token(
                session, 
                token.token
            )
            if validated_token:
                print(f"✓ Token validated successfully: {validated_token.token[:8]}...")
                print(f"  - Duration: {validated_token.duration_hours} hours")
            else:
                print("✗ Token validation failed - token not found or already used")
                return
        except Exception as e:
            print(f"✗ Token validation failed: {e}")
            return
        
        # 4. Test SubscriptionService - Create a subscription
        print("\n4. Testing SubscriptionService - Creating Subscription...")
        try:
            user_id = 987654
            subscriber = await SubscriptionService.register_subscription(
                session,
                user_id=user_id,
                token_id=token.id,
                duration_hours=token.duration_hours
            )
            print(f"✓ VIP subscription created for user {subscriber.user_id}")
            print(f"  - Join date: {subscriber.join_date}")
            print(f"  - Expiry date: {subscriber.expiry_date}")
            print(f"  - Status: {subscriber.status}")
            
            # Check subscription status
            is_active = await SubscriptionService.check_subscription_status(
                session, 
                user_id
            )
            print(f"  - Subscription active: {is_active}")
        except Exception as e:
            print(f"✗ Subscription creation failed: {e}")
            return
        
        # Test ChannelManagementService
        print("\n5. Testing ChannelManagementService...")
        try:
            # Register a free channel request
            request = await ChannelManagementService.register_free_request(
                session, 
                user_id=555555
            )
            print(f"✓ Free channel request registered: ID {request.id}")
            
            # Get pending requests
            pending_requests = await ChannelManagementService.get_pending_requests(
                session
            )
            print(f"✓ Retrieved {len(pending_requests)} pending requests")
            
            # Get VIP channel stats
            vip_stats = await ChannelManagementService.get_channel_stats(
                session, 
                "vip"
            )
            print(f"✓ VIP channel stats: {vip_stats}")
            
            # Get general channel stats
            general_stats = await ChannelManagementService.get_channel_stats(
                session, 
                "general"
            )
            print(f"✓ General channel stats: {general_stats}")
        except Exception as e:
            print(f"✗ ChannelManagementService test failed: {e}")
            return
        
        print("\n✓ All service tests completed successfully!")
        break  # Only need one iteration from the generator


if __name__ == "__main__":
    asyncio.run(test_services())